kind: pipeline
type: docker
name: build

steps:
  - name: docker-build-and-push
    image: plugins/docker
    settings:
      username:
        from_secret: docker_username
      password:
        from_secret: docker_password
      repo: ylin94/alp.base
      tags:
        - latest
        - v3.20.3
      dockerfile: Dockerfile

trigger:
  event:
    - push
    - pull_request
