name: container workflow

description: container workflow.

inputs:
  DOCKER_HUB_USERNAME:
    required: true
  DOCKER_HUB_TOKEN:
    required: true
  QUAY_USERNAME:
    required: true
  QUAY_TOKEN:
    required: true
  IMAGE_NAME:
    required: true
  BASE_IMAGE:
    required: false
    default: latest


runs:
  using: composite
  steps:
    # We require additional space due to the large size of our image.
    - name: Free Disk Space (Ubuntu)
      uses: jlumbroso/free-disk-space@main
      with:
        tool-cache: true
        android: true
        dotnet: true
        haskell: true
        large-packages: true
        docker-images: true
        swap-storage: true

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub Container Registry
      uses: docker/login-action@v3
      with:
        registry: docker.io
        username: ${{ inputs.DOCKER_HUB_USERNAME }}
        password: ${{ inputs.DOCKER_HUB_TOKEN }}

    - name: Login to Quay Container Registry
      uses: docker/login-action@v3
      with:
        registry: quay.io
        username: ${{ inputs.QUAY_USERNAME }}
        password: ${{ inputs.QUAY_TOKEN }}

    - name: Container meta:${{ inputs.BASE_IMAGE }}
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: |
          docker.io/${{ inputs.DOCKER_HUB_USERNAME }}/${{ inputs.IMAGE_NAME }}
          quay.io/${{ inputs.QUAY_USERNAME }}/${{ inputs.IMAGE_NAME }}
        tags: |
          latest


    - name: push container
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        platforms: linux/amd64
        cache-from: type=registry,ref=docker.io/${{ inputs.DOCKER_HUB_USERNAME }}/${{ inputs.IMAGE_NAME }}:cache
        cache-to: type=registry,ref=docker.io/${{ inputs.DOCKER_HUB_USERNAME }}/${{ inputs.IMAGE_NAME }}:cache,mode=max
        sbom: true
        provenance: true